### PR TITLE
[WIP] add initial admin page

### PR DESCRIPTION
**Pull request by anthonyseu**
- [x] Allow admin user to upload topics

screen shot 2017-01-16 at 2 33 40 pm

### CODE REVIEW

**Comment by jacgrady1** [comment]
cool upload topics by using csv?

**Comment by anthonyseu** [comment]
> cool upload topics by using csv?

Yes!

**Comment by anthonyseu** [comment]
@jacgrady1 @quiz1991

**Comment by jacgrady1** [comment]
👍

**Pull request merged**
