### PR TITLE
[UPDATE] topic services API refactor

### PR DESCRIPTION
**Pull request by MichaelGuoXY**
e.g. https://tft.rocks/search?&tag=family,culture,education&level=1,2,3
1. tag=tag1,tag2,tag3
2. level=1,2,3

@jacgrady1 靠人不如靠自己

### CODE REVIEW

**Comment by jacgrady1** [comment]
is it to remove api % codes?

**Comment by MichaelGuoXY** [comment]
array to string

**Comment by jacgrady1** [comment]
So it was an array? The approach should be to make it arrays at earlier steps, right? instead of converting it to strings here?

**Comment by MichaelGuoXY** [comment]
client sends query in string format
server gets query then parsing it into array by split(',')
what do you think, can't get what you mean

**Comment by MichaelGuoXY** [comment]
BTW, say what you mean :D

**Pull request merged**
